import type { ConstitutionRule, ProjectConstitutionDocument, RuleCategory } from '../rules/types.js';

const CATEGORY_HEADINGS: Record<RuleCategory, string> = {
  ARCHITECTURE: 'Architecture',
  CODING_STYLE: 'Frontend / Coding style',
  SECURITY: 'Security',
  DATABASE: 'Database',
  TESTING: 'Testing',
  DEPLOYMENT: 'Deployment',
};

/** Render active (and optionally approved) rules as Project Constitution markdown. */
export function renderConstitutionMarkdown(
  doc: ProjectConstitutionDocument,
  options: { includeSuggested?: boolean } = {},
): string {
  const rules = doc.rules.filter((r) =>
    options.includeSuggested
      ? r.status === 'active' || r.status === 'approved' || r.status === 'suggested'
      : r.status === 'active' || r.status === 'approved',
  );

  const lines = [
    '# Project Constitution',
    '',
    `Project: **${doc.projectName}**`,
    '',
    '_How this project should be developed. Generated by Neuron — CRITICAL changes require human approval._',
    '',
  ];

  for (const category of Object.keys(CATEGORY_HEADINGS) as RuleCategory[]) {
    const items = rules.filter((r) => r.category === category);
    if (!items.length) continue;
    lines.push(`## ${CATEGORY_HEADINGS[category]}`, '');
    for (const r of items) {
      lines.push(`- ${formatRuleBullet(r)}`);
    }
    lines.push('');
  }

  if (doc.mistakes.length) {
    lines.push('## Known mistakes', '');
    for (const m of doc.mistakes.slice(0, 15)) {
      lines.push(`- **${m.title}**: ${m.detail.slice(0, 160)}`);
    }
    lines.push('');
  }

  if (doc.decisions.length) {
    lines.push('## Decision evolution', '');
    for (const d of doc.decisions.slice(0, 15)) {
      lines.push(`- **${d.title}** → ${d.currentState} (v${d.history.length})`);
    }
    lines.push('');
  }

  return `${lines.join('\n').trim()}\n`;
}

function formatRuleBullet(r: ConstitutionRule): string {
  const tag = r.status === 'suggested' ? ' _(suggested)_' : '';
  const sev = r.severity === 'CRITICAL' ? ' **[CRITICAL]**' : r.severity === 'WARNING' ? ' *[warning]*' : '';
  return `${r.rule}${sev}${tag}`;
}

/**
 * Build Cursor `.mdc` rule file from active constitution rules.
 */
export function renderCursorArchitectureRule(doc: ProjectConstitutionDocument): string {
  const active = doc.rules.filter((r) => r.status === 'active');
  const bullets =
    active.length > 0
      ? active.map((r) => `- ${r.rule}`).join('\n')
      : '- Prefer existing project patterns until constitution rules are approved';

  return `---
description: Project architecture rules from Neuron Project Constitution
alwaysApply: true
---

# Project architecture (Neuron Constitution)

Always follow project architecture rules:

${bullets}

## Extra

- Prefer service / repository boundaries when they exist
- Avoid direct database access from controllers when the project forbids it
- Search Neuron memories before inventing a new pattern
- Do **not** invent CRITICAL policy — ask the developer to approve constitution changes
`;
}

export function createCursorRulesFromConstitution(doc: ProjectConstitutionDocument): {
  relativePath: string;
  content: string;
} {
  return {
    relativePath: 'rules/project-architecture.mdc',
    content: renderCursorArchitectureRule(doc),
  };
}
