import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

export interface ProjectBrainInput {
  projectId: string;
  projectName: string;
  stack?: string[];
  architectureNotes?: string[];
  decisions?: Array<{ title: string; content: string }>;
  patterns?: Array<{ title: string; content: string }>;
  warnings?: Array<{ title: string; content: string }>;
}

export interface ProjectBrainPaths {
  projectJson: string;
  architecture: string;
  decisions: string;
  patterns: string;
  warnings: string;
}

export function projectBrainPaths(neuronDir: string): ProjectBrainPaths {
  return {
    projectJson: join(neuronDir, 'project.json'),
    architecture: join(neuronDir, 'architecture.md'),
    decisions: join(neuronDir, 'decisions.md'),
    patterns: join(neuronDir, 'patterns.md'),
    warnings: join(neuronDir, 'warnings.md'),
  };
}

function sectionList(
  heading: string,
  items: Array<{ title: string; content: string }> | undefined,
  emptyHint: string,
): string {
  const lines = [`# ${heading}`, ''];
  if (!items?.length) {
    lines.push(emptyHint, '');
    return lines.join('\n');
  }
  for (const item of items) {
    lines.push(`## ${item.title}`, '', item.content, '');
  }
  return lines.join('\n');
}

export function renderProjectBrain(input: ProjectBrainInput): Record<keyof ProjectBrainPaths, string> {
  const stack = input.stack?.length ? input.stack.join(', ') : 'unknown';
  const archNotes =
    input.architectureNotes?.length
      ? input.architectureNotes.map((n) => `- ${n}`).join('\n')
      : '- (run `neuron analyze` to populate)';

  return {
    projectJson: `${JSON.stringify(
      {
        id: input.projectId,
        name: input.projectName,
        stack: input.stack ?? [],
        generatedAt: new Date().toISOString(),
        gitFriendly: true,
        notes: 'Safe to version in git; do not commit secrets.',
      },
      null,
      2,
    )}\n`,
    architecture: [
      `# Architecture — ${input.projectName}`,
      '',
      `Stack: ${stack}`,
      '',
      '## Notes',
      '',
      archNotes,
      '',
      'Generated by Neuron. Update via memories + `neuron cursor init` / analyze.',
      '',
    ].join('\n'),
    decisions: sectionList(
      `Decisions — ${input.projectName}`,
      input.decisions,
      '_No decisions exported yet. Save with `neuron_save_decision`._',
    ),
    patterns: sectionList(
      `Patterns — ${input.projectName}`,
      input.patterns,
      '_No patterns exported yet._',
    ),
    warnings: sectionList(
      `Warnings — ${input.projectName}`,
      input.warnings,
      '_No warnings exported yet._',
    ),
  };
}

export async function writeProjectBrainFiles(
  neuronDir: string,
  input: ProjectBrainInput,
): Promise<ProjectBrainPaths> {
  const paths = projectBrainPaths(neuronDir);
  const rendered = renderProjectBrain(input);
  await mkdir(neuronDir, { recursive: true });
  await writeFile(paths.projectJson, rendered.projectJson, 'utf8');
  await writeFile(paths.architecture, rendered.architecture, 'utf8');
  await writeFile(paths.decisions, rendered.decisions, 'utf8');
  await writeFile(paths.patterns, rendered.patterns, 'utf8');
  await writeFile(paths.warnings, rendered.warnings, 'utf8');
  return paths;
}

export function templatesRoot(): string {
  const here = dirname(fileURLToPath(import.meta.url));
  // dist/ → dist/templates or package templates/
  return join(here, 'templates');
}

export async function readPackagedTemplate(...parts: string[]): Promise<string> {
  const path = join(templatesRoot(), ...parts);
  return readFile(path, 'utf8');
}
