import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

import type {
  ArchitectureMap,
  DependencyEdge,
  GeneratedMemory,
  ProjectScanReport,
  ProjectStackProfile,
  SuggestedRule,
} from '../types.js';

export class ProjectBrainWriter {
  async write(
    neuronDir: string,
    input: {
      projectName: string;
      stack: ProjectStackProfile;
      architecture: ArchitectureMap;
      dependencyGraph: DependencyEdge[];
      memories: GeneratedMemory[];
      suggestedRules: SuggestedRule[];
      reportMarkdown: string;
      architectureMarkdown: string;
      constitutionMarkdown: string;
    },
  ): Promise<{ architecturePath: string; constitutionPath: string; reportPath: string }> {
    await mkdir(neuronDir, { recursive: true });

    const architecturePath = join(neuronDir, 'architecture.md');
    const constitutionPath = join(neuronDir, 'constitution.md');
    const reportPath = join(neuronDir, 'project-report.md');

    const archDoc = [
      `# ${input.projectName} - Architecture`,
      '',
      '_Generated by Neuron Project Scanner. Review and edit as needed._',
      '',
      '## Technologies',
      '',
      `- Frontend: ${input.stack.frontend.join(', ') || 'n/a'}`,
      `- Backend: ${input.stack.backend.join(', ') || 'n/a'}`,
      `- Database: ${input.stack.database.join(', ') || 'n/a'}`,
      `- Tools: ${input.stack.tools.join(', ') || 'n/a'}`,
      '',
      '## Dependency graph',
      '',
      ...input.dependencyGraph
        .filter((e) => e.relation === 'USES')
        .slice(0, 30)
        .map((e) => `- ${e.from} → ${e.to}`),
      '',
      input.architectureMarkdown,
      '',
      '## Data flow (inferred)',
      '',
      '- Clients → API/controllers → services → repositories/DB',
      '',
    ].join('\n');

    await writeFile(architecturePath, archDoc, 'utf8');
    await writeFile(constitutionPath, input.constitutionMarkdown, 'utf8');
    await writeFile(reportPath, input.reportMarkdown, 'utf8');

    await writeFile(
      join(neuronDir, 'scan-memories.json'),
      JSON.stringify(
        {
          version: 1,
          generatedAt: new Date().toISOString(),
          memories: input.memories,
          suggestedRules: input.suggestedRules,
        },
        null,
        2,
      ),
      'utf8',
    );

    return { architecturePath, constitutionPath, reportPath };
  }

  buildConstitutionMarkdown(projectName: string, rules: SuggestedRule[]): string {
    return [
      `# Suggested Constitution - ${projectName}`,
      '',
      '_These rules are SUGGESTED only. Do not treat as active until reviewed_',
      '_(e.g. `neuron constitution accept` / Project Constitution approval)._',
      '',
      '## Detected patterns → proposed rules',
      '',
      ...rules.map(
        (r, i) =>
          `### ${i + 1}. ${r.rule}\n\n- Confidence: ${Math.round(r.confidence * 100)}%\n- Why: ${r.reason}\n`,
      ),
      rules.length ? '' : '_No high-confidence rules yet - run a deep scan after more code lands._',
      '',
    ].join('\n');
  }

  buildCursorRules(stack: ProjectStackProfile, rules: SuggestedRule[]): string {
    return [
      '---',
      'description: Detected project patterns from Neuron scan (review before relying on them)',
      'globs:',
      'alwaysApply: false',
      '---',
      '',
      '# Project patterns (Neuron bootstrap)',
      '',
      '## Detected conventions',
      '',
      '- Naming / layout: prefer existing module boundaries',
      `- Architecture style: ${stack.backend[0] ?? stack.frontend[0] ?? 'see .neuron/architecture.md'}`,
      `- Preferred libraries: ${[...stack.frontend, ...stack.backend, ...stack.tools].slice(0, 8).join(', ') || 'see package manifests'}`,
      '',
      '## Suggested rules',
      '',
      ...rules.map((r) => `- ${r.rule}`),
      '',
      'Ask Neuron (`neuron_prepare_task`, `neuron_project_map`) before inventing new patterns.',
      '',
    ].join('\n');
  }
}

export function renderProjectReport(report: ProjectScanReport): string {
  return [
    '# Neuron Project Report',
    '',
    `Project: **${report.projectName}**`,
    `Mode: \`${report.mode}\` · Scanned: ${report.scannedAt}`,
    '',
    '## Detected',
    '',
    `- ${report.modules} modules`,
    `- ${report.services} services`,
    `- ${report.dependencies} dependencies`,
    `- ${report.filesScanned} files scanned (${report.filesSkipped} skipped)`,
    '',
    '## Created / suggested',
    '',
    `- ${report.memoriesCreated} memories`,
    `- ${report.relationships} relationships`,
    `- ${report.rulesSuggested} rules (suggested constitution)`,
    '',
    '## Stack',
    '',
    '```',
    createFormatStack(report.stack),
    '```',
    '',
    '## Next',
    '',
    '- Review `.neuron/constitution.md` (suggested only)',
    '- Open project in Cursor - MCP tools are ready',
    '- Prefer `neuron_prepare_task` over inventing architecture',
    '',
  ].join('\n');
}

function createFormatStack(stack: ProjectStackProfile): string {
  return [
    `Frontend: ${stack.frontend.join(', ') || 'n/a'}`,
    `Backend: ${stack.backend.join(', ') || 'n/a'}`,
    `Database: ${stack.database.join(', ') || 'n/a'}`,
    `Tools: ${stack.tools.join(', ') || 'n/a'}`,
  ].join('\n');
}

export function createProjectBrainWriter(): ProjectBrainWriter {
  return new ProjectBrainWriter();
}
