import type {
  SecurityMemory,
  SecurityReviewResult,
  ThreatModel,
} from '../types.js';

/**
 * Render security-report.md — never includes secret values.
 */
export class SecurityReportGenerator {
  markdown(input: {
    overview?: string;
    architectureNotes?: string[];
    review?: SecurityReviewResult;
    threatModel?: ThreatModel;
    previousIncidents?: Array<{ title: string; id?: string }>;
    recommendations?: string[];
  }): string {
    const review = input.review;
    const threats = input.threatModel ?? review?.threatModel;
    const findings = review?.memories ?? [];
    const incidents = input.previousIncidents ?? [];

    const recs = [
      ...(input.recommendations ?? []),
      ...(review?.secrets.map((s) => s.recommendation) ?? []),
      ...(findings.map((f) => f.recommendation).filter(Boolean) as string[]),
      'Human review required before any remediation.',
    ];

    return [
      '# Security Report',
      '',
      '_Generated by Neuron Security Intelligence — local advisor. No secrets stored._',
      '',
      '## Overview',
      '',
      input.overview ??
        review?.patterns.summary ??
        'Local security context review for this project.',
      '',
      '## Architecture',
      '',
      ...(input.architectureNotes?.length
        ? input.architectureNotes.map((n) => `- ${n}`)
        : ['- (no architecture notes provided)']),
      '',
      '## Findings',
      '',
      ...renderFindings(findings),
      '',
      '## Risks',
      '',
      ...(threats?.risks.length
        ? threats.risks.map(
            (r) => `- **${r.severity}** — ${r.risk} (${r.asset} ← ${r.entryPoint})`,
          )
        : ['- No threat risks generated in this pass.']),
      '',
      '## Recommendations',
      '',
      ...[...new Set(recs)].slice(0, 20).map((r) => `- ${r}`),
      '',
      '## Previous incidents',
      '',
      ...(incidents.length
        ? incidents.map((i) => `- ${i.id ? `${i.id}: ` : ''}${i.title}`)
        : ['- None linked.']),
      '',
    ].join('\n');
  }
}

function renderFindings(findings: SecurityMemory[]): string[] {
  if (!findings.length) return ['- No findings in this review.'];
  return findings.map((f) => {
    const loc = f.location ? ` @ ${f.location}` : '';
    return `- **[${f.severity}] ${f.type}** — ${f.description}${loc}`;
  });
}

export function createSecurityReportGenerator(): SecurityReportGenerator {
  return new SecurityReportGenerator();
}
