import type { ProjectBrainSnapshot } from '../types.js';

export function architectureTemplate(brain: ProjectBrainSnapshot): string {
  const name = brain.projectName ?? 'Project';
  const modules = brain.modules?.length ? brain.modules : ['Core'];
  const deps = brain.dependencies ?? [];
  const decisions = brain.decisions ?? [];
  const flows = brain.dataFlows?.length
    ? brain.dataFlows
    : ['Client → API → Services → Database'];
  const risks = brain.securityNotes?.length
    ? brain.securityNotes
    : ['Review auth boundaries and secrets handling'];

  const diagram = [
    '```text',
    '┌─────────┐     ┌─────────┐     ┌──────────┐',
    '│ Client  │────▶│   API   │────▶│ Services │',
    '└─────────┘     └─────────┘     └────┬─────┘',
    '                                     │',
    '                                     ▼',
    '                               ┌──────────┐',
    '                               │ Database │',
    '                               └──────────┘',
    '```',
  ].join('\n');

  return [
    `# ${name} Architecture`,
    '',
    '_Generated by Neuron Documentation Intelligence — review before publishing._',
    '',
    '## Overview',
    '',
    brain.architectureNotes?.join('\n\n') ||
      `${name} is organized around modules: ${modules.join(', ')}.`,
    '',
    '## Architecture diagram',
    '',
    diagram,
    '',
    '## Modules',
    '',
    ...modules.map((m) => `- **${m}**`),
    '',
    '## Data flow',
    '',
    ...flows.map((f) => `- ${f}`),
    '',
    '## Important decisions',
    '',
    ...(decisions.length ? decisions.map((d) => `- ${d}`) : ['- (none recorded)']),
    '',
    '## Dependencies',
    '',
    ...(deps.length ? deps.slice(0, 30).map((d) => `- ${d}`) : ['- (none listed)']),
    '',
    '## Risks',
    '',
    ...risks.map((r) => `- ${r}`),
    '',
  ].join('\n');
}
